const state = { pitches: [], models: [], order: [], index: 0 };
const els = Object.fromEntries(["statusText","pitcherFilter","modelSelect","reviewFilter","progressText","progressBar","prevButton","nextButton","positionText","pitchTitle","plot","modelStatus","modelDetails","pitchVideo","videoStatus","mp4Link","savantLink","pitchDetails","savedReview","reviewNotes"].map(id => [id, document.querySelector(`#${id}`)]));
const xDomain = [-2, 2], yDomain = [-1.5, 2];
function num(value){ if(value === "" || value === null || value === undefined) return null; const parsed=Number(value); return Number.isFinite(parsed)?parsed:null; }
function fmt(value,digits=2){ const parsed=num(value); return parsed===null?"—":parsed.toFixed(digits); }
function esc(value){ return String(value??"—").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); }
function pretty(value){ return String(value||"—").replaceAll("_"," "); }
function currentPitch(){ return state.pitches.find(p=>p.pitch_uid===state.order[state.index])||null; }
function currentModel(pitch=currentPitch()){ return pitch?.models?.[els.modelSelect.value]||{}; }
function reviewed(pitch,modelId){ return Boolean(pitch?.models?.[modelId]?.review?.review_label); }
function available(model){ return ["provisional","baseline"].includes(model?.status); }

function rebuildOrder(keepUid=currentPitch()?.pitch_uid){
  let rows=state.pitches.filter(p=>els.pitcherFilter.value==="All Pitchers"||p.sample_pitcher_name===els.pitcherFilter.value);
  const filter=els.reviewFilter.value, modelId=els.modelSelect.value;
  if(filter==="reviewed") rows=rows.filter(p=>reviewed(p,modelId));
  if(filter==="available") rows=rows.filter(p=>available(p.models?.[modelId]));
  rows.sort((a,b)=> filter==="pending" ? Number(reviewed(a,modelId))-Number(reviewed(b,modelId)) || String(a.game_date).localeCompare(String(b.game_date)) : String(a.sample_pitcher_name+a.game_date+a.pitch_uid).localeCompare(String(b.sample_pitcher_name+b.game_date+b.pitch_uid)));
  state.order=rows.map(p=>p.pitch_uid); state.index=Math.max(0,state.order.indexOf(keepUid)); if(!state.order.includes(keepUid)) state.index=0;
}
function pctX(x){ return 100*(x-xDomain[0])/(xDomain[1]-xDomain[0]); }
function pctY(y){ return 100*(yDomain[1]-y)/(yDomain[1]-yDomain[0]); }
function addPoint(className,x,y,title){ if(num(x)===null||num(y)===null)return; const node=document.createElement("div"); const rawX=pctX(Number(x)),rawY=pctY(Number(y)); node.className=`point ${className}${rawX<1||rawX>99||rawY<1||rawY>99?" clipped":""}`; node.style.left=`${Math.max(1,Math.min(99,rawX))}%`; node.style.top=`${Math.max(1,Math.min(99,rawY))}%`; node.title=`${title}: ${fmt(x)}, ${fmt(y)}`; els.plot.append(node); }
function renderPlot(pitch,model){
  els.plot.innerHTML=""; const zone=document.createElement("div"); zone.className="strike-zone"; zone.style.left=`${pctX(0)}%`; zone.style.top=`${pctY(1)}%`; zone.style.width=`${pctX(1)-pctX(0)}%`; zone.style.height=`${pctY(0)-pctY(1)}%`; for(const left of [33.333,66.666]){const line=document.createElement("i");line.className="zone-vline";line.style.left=`${left}%`;zone.append(line);} els.plot.append(zone);
  const rx1=num(model.region_x_low_01),rx2=num(model.region_x_high_01),ry1=num(model.region_y_low_01),ry2=num(model.region_y_high_01);
  if([rx1,rx2,ry1,ry2].every(v=>v!==null)){ const region=document.createElement("div");region.className="finish-region";region.style.left=`${pctX(rx1)}%`;region.style.top=`${pctY(ry2)}%`;region.style.width=`${pctX(rx2)-pctX(rx1)}%`;region.style.height=`${pctY(ry1)-pctY(ry2)}%`;els.plot.append(region); }
  addPoint("detector",pitch.detector_target_x_01,pitch.detector_target_y_01,"Detector target"); addPoint("audited",pitch.model_target_x_01,pitch.model_target_y_01,"Audited target"); if(available(model)) addPoint("inferred",model.intent_x_01,model.intent_y_01,"Inferred target"); addPoint("actual",pitch.actual_x_01,pitch.actual_y_01,"Actual pitch");
}
function render(){
  const pitch=currentPitch(),model=currentModel(pitch),modelId=els.modelSelect.value; const allForModel=state.pitches.filter(p=>(els.pitcherFilter.value==="All Pitchers"||p.sample_pitcher_name===els.pitcherFilter.value)&&available(p.models?.[modelId])); const reviewCount=allForModel.filter(p=>reviewed(p,modelId)).length;
  els.progressText.textContent=`${reviewCount} of ${allForModel.length} reviewed for this model`; els.progressBar.style.width=`${allForModel.length?100*reviewCount/allForModel.length:0}%`; els.positionText.textContent=`Pitch ${state.order.length?state.index+1:0} of ${state.order.length}`; els.prevButton.disabled=state.index<=0; els.nextButton.disabled=state.index>=state.order.length-1;
  if(!pitch){ els.pitchTitle.textContent="No pitches match this filter"; els.plot.innerHTML=""; return; }
  els.pitchTitle.textContent=`${pitch.sample_pitcher_name} · ${pitch.pitch_name} · ${pitch.game_date} · ${pitch.balls}-${pitch.strikes}`; renderPlot(pitch,model);
  const status=model.status||"missing"; els.modelStatus.textContent=available(model)?`${pretty(status)} estimate · ${model.evidence_tier?`${model.evidence_tier} evidence`:"baseline"}`:`No inferred target: ${pretty(status)}`;
  els.modelDetails.innerHTML=[["Model",state.models.find(m=>m.id===modelId)?.label||modelId],["Inferred target",`${fmt(model.intent_x_01)}, ${fmt(model.intent_y_01)}`],["Comparable pitches",model.candidate_n||model.prior_group_n||"—"],["Effective support",fmt(model.effective_n,1)],["Expected shape",model.expected_pfx_x?`${fmt(model.expected_pfx_x)} x · ${fmt(model.expected_pfx_z)} z · ${fmt(model.expected_release_speed,1)} mph`:"—"],["Region",model.region_area_sqft?`${fmt(model.region_area_sqft)} sq ft`:"—"],["Detector status",pretty(pitch.detector_status)]].map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join("");
  const source=pitch.direct_mp4_url||""; if(els.pitchVideo.dataset.src!==source){els.pitchVideo.dataset.src=source;els.pitchVideo.src=source;els.pitchVideo.load();} els.videoStatus.textContent=source?"Video available":"No video"; els.mp4Link.href=source||"#"; els.mp4Link.style.visibility=source?"visible":"hidden"; els.savantLink.href=pitch.savant_video_url||"#"; els.savantLink.style.visibility=pitch.savant_video_url?"visible":"hidden";
  els.pitchDetails.innerHTML=[["Pitch ID",pitch.pitch_uid],["Situation",`${pitch.inning_topbot} ${pitch.inning} · ${pitch.balls}-${pitch.strikes}`],["Result",pitch.events||pitch.description],["Actual plate",`${fmt(pitch.plate_x)} x · ${fmt(pitch.plate_z)} z ft`],["Pitch shape",`${fmt(pitch.release_speed,1)} mph · ${fmt(pitch.release_spin_rate,0)} rpm · ${fmt(pitch.pfx_x)} x · ${fmt(pitch.pfx_z)} z`]].map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join("");
  const review=model.review||{}; els.savedReview.textContent=review.review_label?`${pretty(review.review_label)} · ${review.reviewed_at||"saved"}`:available(model)?"Not reviewed":"No estimate to review"; els.reviewNotes.value=review.review_notes||""; els.reviewNotes.disabled=!available(model); document.querySelectorAll("[data-review]").forEach(button=>{button.classList.toggle("active",button.dataset.review===review.review_label);button.disabled=!available(model);});
}
function navigate(delta){const next=state.index+delta;if(next<0||next>=state.order.length)return;state.index=next;render();}
async function saveReview(label){const pitch=currentPitch(),modelId=els.modelSelect.value;if(!pitch)return; const response=await fetch("/api/intent-audit-label",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pitch_uid:pitch.pitch_uid,model:modelId,review_label:label,review_notes:els.reviewNotes.value.trim(),sample_pitcher_name:pitch.sample_pitcher_name,pitch_type:pitch.pitch_type})});if(!response.ok)throw new Error(await response.text());const data=await response.json();pitch.models[modelId].review=data.review;const next=state.order.findIndex((uid,index)=>index>state.index&&!reviewed(state.pitches.find(p=>p.pitch_uid===uid),modelId));if(next>=0)state.index=next;rebuildOrder(currentPitch()?.pitch_uid);render();}
els.prevButton.addEventListener("click",()=>navigate(-1));els.nextButton.addEventListener("click",()=>navigate(1)); for(const el of [els.pitcherFilter,els.modelSelect,els.reviewFilter])el.addEventListener("change",()=>{rebuildOrder();render();});document.querySelectorAll("[data-review]").forEach(button=>button.addEventListener("click",()=>saveReview(button.dataset.review).catch(error=>{els.savedReview.textContent=`Save failed: ${error.message}`})));
window.addEventListener("keydown",event=>{if(["INPUT","SELECT","VIDEO"].includes(document.activeElement?.tagName))return;if(event.key==="ArrowLeft")navigate(-1);if(event.key==="ArrowRight")navigate(1);});
async function load(){const response=await fetch("/api/intent-audit");if(!response.ok)throw new Error(await response.text());const data=await response.json();state.pitches=data.pitches||[];state.models=data.models||[];els.pitcherFilter.innerHTML=["All Pitchers",...new Set(state.pitches.map(p=>p.sample_pitcher_name))].map(v=>`<option>${esc(v)}</option>`).join("");els.modelSelect.innerHTML=state.models.map(m=>`<option value="${esc(m.id)}">${esc(m.label)}</option>`).join("");els.statusText.textContent=`${data.pitch_count} audited pitches · compare five intent estimates`;rebuildOrder(null);render();}
load().catch(error=>{els.statusText.textContent=`Load failed: ${error.message}`;});
